spring.application.name=crimeArchive
#Show sql queries
spring.jpa.show-sql=true
#create table automatic, understand flyway operartion and change this to validate
spring.jpa.hibernate.ddl-auto=update
#oauth client repository dependency
spring.security.oauth2.client.registration.github.client-id=Ov23lijdkuEENoH2xJzA
spring.security.oauth2.client.registration.github.client-secret=7b7f2e2c69e5b1c7dc71b5b6ca43b5757211292c
# keep container alive between restarts
spring.docker.compose.lifecycle-management=start_only

# Debug trace
logging.level.org.springframework.security=debug
#spring.sql.init.data-locations=staticDatabase
#spring.sql.init.mode=always
